# Tell the application it is being booted by MCUboot.
# This forces Zephyr to leave 32-bytes of empty space at the start 
# of the binary so imgtool can inject the cryptographic header later.
CONFIG_BOOTLOADER_MCUBOOT=y

CONFIG_PRINTK=y